server.port=8080

# !!!! Настройки для раздела spring.kafka хранятся в фале KafkaProperties.class (файл можно найти через поиск) !!!!

# группа в которой будут topic
spring.kafka.producer.group-id="car-part-kafka-group"

# topic которые используются в сервисе
application.kafka.topics=carpart-topic,analog-topic

# брокер к которому будем подключаться (указан в docker-compose.yml, секция kafka)
spring.kafka.producer.bootstrap-servers="127.0.0.1:29092"

# идентификатор клиента, под которым будем подключаться
# "ID to pass to the server when making requests. Used for server-side logging." из файла KafkaProperties.class
spring.kafka.producer.client-id="carpart-producer-client-id"
