server:
  port: 8080

# !!!! Настройки для раздела spring.kafka хранятся в фале KafkaProperties.class (файл можно найти через поиск) !!!!

# topic которые используются в сервисе
my_service:
  kafka:
    topics:
      topic_1:
        name: "carpart-topic"

spring:
  kafka:
    producer:
      # группа в которой будут topic
      group-id: ${spring.application.name} #"car-part-kafka-group"
      # брокер к которому будем подключаться (указан в docker-compose.yml, секция kafka)
      bootstrap-servers: "127.0.0.1:9092"
      # идентификатор клиента, под которым будем подключаться
      # "ID to pass to the server when making requests. Used for server-side logging." из файла KafkaProperties.class
      client-id: "carpart-producer-client-id"
      # Для отладки. На продакшене этот параметр не нужен.
      # Параметр указывает с какого смещения будем начинать читать (начиная с какого-то сообщения, что бы несколько раз не отправлять
      # сообщение)
      auto-offset-reset: earliest