spring:
  sql:
    init:
      data-locations: classpath:carpart-test.sql #Locations of the data (DML) scripts to apply to the database.
      mode: always # initialize an SQL database
  messages:
    basename: i18n.messages
    fallback-to-system-locale: false
  datasource:
    url: jdbc:h2:mem:testdb
    schema: classpath:schema.sql
#      data: classpath:carpart-test.sql #Spring boot verion 2.7 and onwards is not any more depracated.
#      initialization-mode: always #Spring boot verion 2.7 and onwards is not any more depracated.
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
logging:
  level:
    ROOT: ERROR