spring:
  sql:
    init:
      data-locations: classpath:data.sql #Locations of the data (DML) scripts to apply to the database.
      mode: always # initialize an SQL database
  messages:
    basename: i18n.messages
    fallback-to-system-locale: false
  datasource:
    url: jdbc:h2:mem:CarPartDB
    schema: classpath:schema.sql
    driver: org.h2.Driver
    password:
    username: sa
#      data: classpath:carpart-test.sql #Spring boot verion 2.7 and onwards is not any more depracated.
#      initialization-mode: always #Spring boot verion 2.7 and onwards is not any more depracated.
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
logging:
  level:
    ROOT: ERROR
    com:
      querydsl:
        sql: DEBUG #is for logging statements in querydsl
  pattern:
    console: KAPOROV %d{dd-MM-yyyy HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n