server:
  port: 8080
spring:
  sql:
    init:
      data-locations: #classpath:data.sql #Locations of the data (DML) scripts to apply to the database.
      mode: always # initialize an SQL database
  messages:
    basename: i18n.messages
    fallback-to-system-locale: false
  datasource:
    password: cp_PostgreSQL
    username: cp_usr
    url: jdbc:postgresql://localhost:5430/CarPartDB_Docker
    schema: classpath:schema.sql
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none #отключаем автоматическое создание схемы Hibernate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: false
logging:
  level:
    ROOT: ERROR
    com:
      querydsl:
        sql: DEBUG #is for logging statements in querydsl
  pattern:
    console: KAPOROV-Docker-application-yml %d{dd-MM-yyyy HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n