server:
  port: ${APPLICATION_PORT_DOCKER}
spring:
  sql:
    init:
      data-locations: #classpath:data.sql #Locations of the data (DML) scripts to apply to the database.
      mode: always # initialize an SQL database
  messages:
    basename: i18n.messages
    fallback-to-system-locale: false
  datasource:
    url: ${APPLICATION_DATASOURCE_URL_DOCKER}
    password: ${APPLICATION_DATASOURCE_PASSWORD_DOCKER}
    username: ${APPLICATION_DATASOURCE_USER_DOCKER}
    schema: classpath:schema.sql # todo Закоментарить после создания Docker-Image и упаковки приложения в контейнер
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none #отключаем автоматическое создание схемы Hibernate
    properties:
      hibernate:
        format_sql: false
logging:
  level:
    ROOT: ERROR
    com:
      querydsl:
        sql: DEBUG #is for logging statements in querydsl
  pattern:
    console: KAPOROV-Docker-App %d{dd-MM-yyyy HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n